#Based on https://ci.salto.io/ && https://sfdx-hardis.cloudity.com/
on:
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened]
    paths:
      - 'force-app/**'

name: Validation SFDX Hardis

jobs:
  check_deployment:
    runs-on: ubuntu-latest
    name: Simulate Deployment to Major Org
    permissions:
      pull-requests: write
    env:
      SFDX_CLIENT_ID_MAIN: ${{ secrets.SFDX_CLIENT_ID_MAIN}}
      SFDX_CLIENT_KEY_MAIN: ${{ secrets.SFDX_CLIENT_KEY_MAIN}}
      SFDX_DEPLOY_WAIT_MINUTES: 120 # Override if necessary
      SFDX_TEST_WAIT_MINUTES: 120 # Override if necessary
      CI_COMMIT_REF_NAME: ${{ github.event.pull_request.base.ref }} # Defines the target branch of the PR
      ORG_ALIAS: ${{ github.event.pull_request.base.ref }} # Defines the target branch of the PR
      CONFIG_BRANCH: ${{ github.event.pull_request.base.ref }} # Defines the target branch of the PR
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      FORCE_COLOR: "1"
    steps:
    # Checkout repo
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Faster code checkout fetching only latest commit
    # Setup node
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: "20"
    # tests to run
    - name: 'Selecting Tests to Run from PR Body'
      env:
        PR_BODY: ${{github.event.pull_request.body}}´
      run: |
        echo $PR_BODY > ./pr_body.txt
        node ./parsePR.js   
        cat testsToRun.txt           
        TESTS=$(cat testsToRun.txt)       
        echo "APEX_TESTS=$TESTS" >> $GITHUB_ENV    
    # SFDX & plugins
    - name: Install SFDX and plugins
      run: |
        npm install --no-cache @salesforce/cli --global
        echo 'y' | sf plugins:install sfdx-git-delta
        echo 'y' | sf plugins:install @salesforce/sfdx-scanner
        echo 'y' | sf plugins:install sfdx-hardis
    # Calculate delta (set package.xml = delta.xml) to deploy only delta changes and set destructive
    - name: Configure delta changes and destructive
      run: |
        mkdir changed-sources
        sf sgd:source:delta --to "HEAD" --from "HEAD^" --output changed-sources/ --generate-delta --source force-app/
        echo $(cat changed-sources/package/package.xml) > manifest/package.xml
        DESTRUCTIVE=$(cat changed-sources/destructiveChanges/destructiveChanges.xml | tr -d '[:space:]''?'\''/\\')       
        echo "DESTRUCTIVE_PACKAGE=$DESTRUCTIVE" >> $GITHUB_ENV
    # Scanner
    - name: 'Scan code'
      run: |
        sf scanner:run --format sarif --target './**/*.cls' --category "Design,Best Practices,Performance" --outfile 'apexScanResults.sarif'  
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: apexScanResults.sarif
    #login
    - name: Salesforce Authentication
      run:
        sf hardis:auth:login
    # Check deploy runnning All Tests
    - name: Simulate delta deployment - All Tests
      if: ${{env.APEX_TESTS == 'all'}}
      run:
        sf hardis:project:deploy:smart --check --testlevel RunLocalTests
    # Check deploy runnning Selected Tests
    - name: Simulate delta deployment - Selected Tests
      if: ${{env.APEX_TESTS != 'all'}}
      run:
        sf hardis:project:deploy:smart --check --testlevel RunSpecifiedTests -r ${{env.APEX_TESTS}}
    # Separate async destructive    
    - name: 'Check destructive changes (if any)'
      if: contains(env.DESTRUCTIVE_PACKAGE, '<types>')
      run: |
        cat changed-sources/destructiveChanges/destructiveChanges.xml
        sf project deploy start --dry-run --async --pre-destructive-changes changed-sources/destructiveChanges/destructiveChanges.xml --manifest changed-sources/destructiveChanges/package.xml --ignore-warnings